[package]
name = "rust-semaphore"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_futures"] }

[[bench]]
name = "semaphore_benchmark"
harness = false
