[package]
name = "rust-semaphore"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
criterion = "0.3"

[lib]
name = "rust_semaphore"
path = "src/lib.rs"

[profile.release]
debug = true
