name: Benchmark

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: cargo build --release

  benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run benchmarks
      run: cargo bench -- --save-baseline new

    - name: List Benchmark Directory
      run: ls -al target/criterion/semaphore_benchmark

  upload:
    runs-on: ubuntu-latest
    needs: benchmark

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Upload benchmark results to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
        aws s3 cp target/criterion/semaphore_benchmark/new s3://switch-benchs/${BRANCH_NAME}/baseline.bench --region ***
