name: Benchmark

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      run: cargo build --release

    - name: Run benchmarks
      run: cargo bench --bench semaphore_benchmark -- --save-baseline main

    - name: Debug - List contents of target directory
      run: |
        echo "Contents of target directory:"
        ls -R target

    - name: Debug - Find benchmark results
      run: |
        echo "Searching for benchmark results:"
        find target -name "new" -type d

    - name: Upload benchmark results to GitHub Actions artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmark-results
        path: target/criterion
        if-no-files-found: warn

    - name: Upload benchmark results to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
        BENCHMARK_DIR=$(find target/criterion -name "new" -type d | head -n 1)
        if [ -z "$BENCHMARK_DIR" ]; then
          echo "Benchmark results directory not found"
          exit 1
        fi
        aws s3 cp $BENCHMARK_DIR s3://switch-benchs/${BRANCH_NAME}/baseline.bench --recursive --region us-east-1